PRODUCTS_DB = [
    # ==================== SERUMS (10 Products) ====================
    {
        "id": 1,
        "title": "Glow Vitamin C Serum",
        "category": "Serums",
        "brand": "The Ordinary",
        "image": "image/product_1.jpg",
        "price": 28.00,
        "qty": 50,
        "description": "Brightening serum formulated with 10% Vitamin C and Ferulic acid to fade dark spots.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply 2-3 drops to clean face in the AM. Follow with moisturizer and sunscreen.",
        "ingredients": "Water, Ascorbic Acid (Vitamin C), Ethoxydiglycol, Ferulic Acid, Sodium Hyaluronate, Phenoxyethanol."
    },
    {
        "id": 2,
        "title": "Hydrating Hyaluronic Booster",
        "category": "Serums",
        "brand": "CeraVe",
        "image": "image/product_2.jpg",
        "price": 24.50,
        "qty": 110,
        "description": "Multi-molecular weight hyaluronic acid for deep, multi-layer skin hydration.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply evenly to face and neck daily after cleansing. Can be used AM and PM.",
        "ingredients": "Water, Glycerin, Sodium Hyaluronate, Sodium Acetylated Hyaluronate, Ceramide NP, Ceramide AP, Phenoxyethanol."
    },
    {
        "id": 3,
        "title": "Overnight Retinol Repair",
        "category": "Serums",
        "brand": "La Roche-Posay",
        "image": "image/product_3.jpg",
        "price": 34.00,
        "qty": 45,
        "description": "0.5% Encapsulated retinol to target fine lines, wrinkles, and uneven skin texture.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply a pea-sized amount at night (PM) to clean, dry skin. Limit initial use to 2-3 times a week.",
        "ingredients": "Water, Glycerin, Retinol, Polysorbate 20, Niacinamide, Tocopherol (Vitamin E), Ammonium Polyacryloyldimethyl Taurate."
    },
    {
        "id": 4,
        "title": "Niacinamide 10% Pore Minimizer",
        "category": "Serums",
        "brand": "The Ordinary",
        "image": "image/product_4.jpg",
        "price": 22.00,
        "qty": 80,
        "description": "Blemish control serum that regulates sebum production and visibly tightens pores.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply to entire face morning and evening before heavier creams.",
        "ingredients": "Water, Niacinamide, Zinc PCA, Tamarindus Indica Seed Gum, Pentylene Glycol, Xanthan Gum, Phenoxyethanol."
    },
    {
        "id": 5,
        "title": "Salicylic Acid 2% Acne Serum",
        "category": "Serums",
        "brand": "Paula's Choice",
        "image": "image/product_5.jpg",
        "price": 23.00,
        "qty": 60,
        "description": "Exfoliating liquid treatment that penetrates deep into pores to eliminate acne breakouts.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply once or twice daily after cleansing/toning. Smooth gently over the face or target acne zones.",
        "ingredients": "Water, Methylpropanediol, Salicylic Acid, Camellia Oleifera (Green Tea) Leaf Extract, Polysorbate 20, Sodium Hydroxide."
    },
    {
        "id": 6,
        "title": "Multi-Peptide Firming Elixir",
        "category": "Serums",
        "brand": "The Inkey List",
        "image": "image/product_6.jpg",
        "price": 38.00,
        "qty": 30,
        "description": "Advanced peptide technology designed to restore structural elasticity and skin plumpness.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Use AM and PM. On cleansed skin apply a pea-sized amount to face and neck.",
        "ingredients": "Water, Propanediol, Butylene Glycol, Acetyl Hexapeptide-8, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Phenoxyethanol."
    },
    {
        "id": 29,
        "title": "Probiotic Skin Barrier Serum",
        "category": "Serums",
        "brand": "Glow Recipe",
        "image": "image/product_29.jpg",
        "price": 36.00,
        "qty": 55,
        "description": "Strengthens skin microbiome with fermented probiotics and nourishing rice extracts.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Pat 1-2 pumps onto clean skin. Use daily in morning and evening routines.",
        "ingredients": "Water, Lactobacillus Ferment Lysate, Saccharomyces Ferment Filtrate, Rice Bran Extract, Glycerin, Sodium Hyaluronate."
    },
    {
        "id": 30,
        "title": "Alpha Arbutin 2% Hyper-Pigmentation Serum",
        "category": "Serums",
        "brand": "The Ordinary",
        "image": "image/product_30.jpg",
        "price": 21.00,
        "qty": 75,
        "description": "Concentrated serum to visibly fade dark spots, sun spots, and post-acne marks.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply a few drops to the face in morning and night as part of your skincare regimen.",
        "ingredients": "Water, Alpha-Arbutin, Polyacrylate Crosspolymer-6, Hydrolyzed Sodium Hyaluronate, Propanediol, Lactic Acid."
    },
    {
        "id": 31,
        "title": "Coenzyme Q10 Antioxidant Serum",
        "category": "Serums",
        "brand": "The Inkey List",
        "image": "image/product_31.jpg",
        "price": 19.50,
        "qty": 90,
        "description": "Powerful antioxidant protection that shields skin from pollution and stress factors.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Use AM and PM. Smooth a pea-sized amount onto targeted facial skin structures.",
        "ingredients": "Water, Ubiquinone (Q10), Tocopheryl Acetate, Squalane, Glycerin, Phospholipids, Sodium Citrate."
    },
    {
        "id": 32,
        "title": "Azelaique Acid 10% Clarifying Cream-Serum",
        "category": "Serums",
        "brand": "Paula's Choice",
        "image": "image/product_32.jpg",
        "price": 28.00,
        "qty": 40,
        "description": "Multitasking formula reduces redness, brightens skin tone, and smooths bumps.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply once or twice daily after cleansing and toning. Wear under daytime SPF 30+.",
        "ingredients": "Water, Azelaic Acid, C12-15 Alkyl Benzoate, Glycerin, Salicylic Acid, Glycyrrhiza Glabra (Licorice) Root Extract, Allantoin."
    },

    # ==================== CLEANSERS (9 Products) ====================
    {
        "id": 7,
        "title": "Gentle Amino Foaming Cleanser",
        "category": "Cleansers",
        "brand": "Cetaphil",
        "image": "image/product_7.jpg",
        "price": 18.50,
        "qty": 85,
        "description": "A pH-balanced, non-stripping cleanser that removes makeup and impurities gently.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Massage foam onto wet face. Rinse thoroughly with clean water. Use daily morning and night.",
        "ingredients": "Water, Sodium Cocoyl Glycinate, Coco-Betaine, Glycerin, Sodium Chloride, Citric Acid, Sodium Benzoate."
    },
    {
        "id": 8,
        "title": "Salicylic Acid Purifying Gel",
        "category": "Cleansers",
        "brand": "COSRX",
        "image": "image/product_8.jpg",
        "price": 19.00,
        "qty": 60,
        "description": "Targeted BHA treatment cleanser designed to clear pores and reduce breakouts.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply to wet skin, massage gently into lather, concentrating on breakout zones, then wash off.",
        "ingredients": "Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Salicylic Acid, Melaleuca Alternifolia (Tea Tree) Leaf Oil."
    },
    {
        "id": 9,
        "title": "Centella Calming Cleansing Balm",
        "category": "Cleansers",
        "brand": "Skin1004",
        "image": "image/product_9.jpg",
        "price": 22.00,
        "qty": 40,
        "description": "Sorbet-like melting balm that dissolves stubborn waterproof makeup effortlessly.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Scoop a small amount with spatula. Massage over dry face. Splash water to emulsify, then rinse.",
        "ingredients": "Ethylhexyl Palmitate, Cetyl Ethylhexanoate, PEG-20 Glyceryl Triisostearate, Centella Asiatica Extract, Simmondsia Chinensis (Jojoba) Seed Oil."
    },
    {
        "id": 10,
        "title": "Hydrating Milk Wash",
        "category": "Cleansers",
        "brand": "Aveeno",
        "image": "image/product_10.jpg",
        "price": 17.00,
        "qty": 90,
        "description": "Soothes dry, sensitive skin with oat kernel extracts while dissolving debris.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Wet skin with lukewarm water. Massage 1-2 pumps into skin with a gentle, circular motion, wipe or rinse off.",
        "ingredients": "Water, Cetearyl Alcohol, Glycerin, Avena Sativa (Oat) Kernel Flour, Xanthan Gum, Ethylhexylglycerin, Sodium Benzoate."
    },
    {
        "id": 11,
        "title": "Matcha Deep Clean Clay Mask Wash",
        "category": "Cleansers",
        "brand": "Some By Mi",
        "image": "image/product_11.jpg",
        "price": 21.50,
        "qty": 55,
        "description": "Antioxidant-rich green tea clay that works double time as a wash-off clarifying pore scrub.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply a thick layer to dry face. After 10-15 minutes, massage with warm water and rinse out thoroughly.",
        "ingredients": "Water, Kaolin, Camellia Sinensis (Matcha) Leaf Extract, Glycerin, Bentonite, Silica, Centella Asiatica Extract."
    },
    {
        "id": 33,
        "title": "Low pH Good Morning Gel Cleanser",
        "category": "Cleansers",
        "brand": "COSRX",
        "image": "image/product_33.jpg",
        "price": 16.50,
        "qty": 130,
        "description": "Gentle daily gel cleanser formulated with tea tree oil to balance oily skin zones.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Gently massage a small amount of this gel cleanser on wet skin. Rinse with lukewarm water.",
        "ingredients": "Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Styrax Japonicus Branch/Fruit/Leaf Extract, Cryptomeria Japonica Leaf Extract."
    },
    {
        "id": 34,
        "title": "Ginseng Cleansing Oil",
        "category": "Cleansers",
        "brand": "Beauty of Joseon",
        "image": "image/product_34.jpg",
        "price": 23.00,
        "qty": 65,
        "description": "Lightweight cleansing oil that gently emulsifies and melts away waterproof cosmetics.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "how_to_use": "Pump 1-2 times onto dry hands and massage gently over dry face. Rinse with warm water.",
        "ingredients": "Glycine Soja (Soybean) Oil, Cetyl Ethylhexanoate, Panax Ginseng Seed Oil, Olive Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil."
    },
    {
        "id": 35,
        "title": "Heartleaf Pore Cleansing Foam",
        "category": "Cleansers",
        "brand": "Anua",
        "image": "image/product_35.jpg",
        "price": 19.00,
        "qty": 80,
        "description": "Deeply purifies pore systems while soothing active skin redness with heartleaf extract.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Dampen skin. Rub a pea-sized amount between palms until rich, apply on skin, then wash off with clean water.",
        "ingredients": "Houttuynia Cordata Extract (Heartleaf), Sodium Cocoyl Glycinate, Glycerin, Sodium Lauroyl Glutamate, Lauryl Betaine."
    },
    {
        "id": 36,
        "title": "Squalane Melting Cleanser Cream",
        "category": "Cleansers",
        "brand": "Biossance",
        "image": "image/product_36.jpg",
        "price": 26.00,
        "qty": 45,
        "description": "A rich cream-to-oil formulation protecting foundational moisture while removing impurities.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Rub cream over skin surfaces. Rub gently until it feels like fine facial oil, then rinse thoroughly.",
        "ingredients": "Squalane, Caprylic/Capric Tryglyceride, Glycerin, Water, Sucrose Laurate, Tocopherol (Vitamin E)."
    },

    # ==================== MOISTURIZERS (10 Products) ====================
    {
        "id": 12,
        "title": "Ultra Barrier Ceramide Cream",
        "category": "Moisturizers",
        "brand": "CeraVe",
        "image": "image/product_12.jpg",
        "price": 32.00,
        "qty": 40,
        "description": "Deeply hydrating moisturizer packed with 3 essential ceramides to repair skin barriers.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply liberally to face and neck as often as needed, or as directed by a dermatologist.",
        "ingredients": "Water, Glycerin, Cetearyl Alcohol, Ceramide NP, Ceramide AP, Ceramide EOP, Cholesterol, Phytosphingosine, Hyaluronic Acid."
    },
    {
        "id": 13,
        "title": "Daily Water-Gel Hydrator",
        "category": "Moisturizers",
        "brand": "Neutrogena",
        "image": "image/product_13.jpg",
        "price": 26.00,
        "qty": 95,
        "description": "Oil-free, ultra-lightweight gel moisturizer perfect for oily and combination skin types.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply evenly to face and neck daily after cleansing. Absorbs quickly into skin layers.",
        "ingredients": "Water, Dimethicone, Glycerin, Cetearyl Olivate, Sorbitan Olivate, Sodium Hyaluronate, Phenoxyethanol."
    },
    {
        "id": 14,
        "title": "Bakuchiol Age-Renewal Cream",
        "category": "Moisturizers",
        "brand": "Inkey List",
        "image": "image/product_14.jpg",
        "price": 36.50,
        "qty": 35,
        "description": "A plant-based retinol alternative cream that firms skin and enhances youthful radiance.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Use AM and PM. Apply a pea-sized amount to cleansed face and neck layers.",
        "ingredients": "Water, Propanediol, Squalane, Bakuchiol, Cetearyl Alcohol, Plukenetia Volubilis Seed Oil, Sodium Hyaluronate."
    },
    {
        "id": 15,
        "title": "Vitamin E Intense Relief Lotion",
        "category": "Moisturizers",
        "brand": "The Body Shop",
        "image": "image/product_15.jpg",
        "price": 25.00,
        "qty": 70,
        "description": "Locks down long-lasting continuous environmental protection for flaky skin patches.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Smooth gently onto skin surfaces using fingertips. Ideal for skin needing intense relief hydration.",
        "ingredients": "Water, Tocopheryl Acetate (Vitamin E), Glycerin, Cyclohexasiloxane, Butyrospermum Parkii (Shea Butter), Citric Acid."
    },
    {
        "id": 16,
        "title": "Squalane Multi-Layer Cloud Gel",
        "category": "Moisturizers",
        "brand": "Biossance",
        "image": "image/product_16.jpg",
        "price": 29.00,
        "qty": 65,
        "description": "Feather-light squalane base fluid that whipped into an airy cream format.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "how_to_use": "Apply onto clean facial surface both morning and evening to achieve cloud-soft skin effects.",
        "ingredients": "Water, Squalane, Glycerin, Sodium Hyaluronate, Hydrolyzed Rice Protein, Malachite Extract, Ethylhexylglycerin."
    },
    {
        "id": 17,
        "title": "Overnight Recovery Sleeping Pack",
        "category": "Moisturizers",
        "brand": "Laneige",
        "image": "image/product_17.jpg",
        "price": 31.00,
        "qty": 48,
        "description": "An intense nighttime moisture mask wrapping complex nutrients over skin layers during sleep cycles.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply evenly across face at night. Leave on overnight and rinse thoroughly next morning.",
        "ingredients": "Water, Dimethicone, Squalane, Glycerin, Trehalose, Cyclohexasiloxane, Salvia Hispanica Seed Extract, Magnesium Sulfate."
    },
    {
        "id": 37,
        "title": "Dynasty Cream Elegant Glow",
        "category": "Moisturizers",
        "brand": "Beauty of Joseon",
        "image": "image/product_37.jpg",
        "price": 27.50,
        "qty": 70,
        "description": "Enriched with Hanbang traditional ingredients to provide firm and glowing hydration.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply an appropriate amount on your face at the last stage of your skincare routine.",
        "ingredients": "Water, Oryza Sativa (Rice) Bran Water, Panax Ginseng Root Water, Glycerin, Niacinamide, Squalane, Coconut Oil."
    },
    {
        "id": 38,
        "title": "Vitamin C Gel-Cream Radiance Boost",
        "category": "Moisturizers",
        "brand": "The Body Shop",
        "image": "image/product_38.jpg",
        "price": 28.50,
        "qty": 50,
        "description": "Light refreshing texture that clarifies dull complexions and re-energizes fatigued skin.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Massage into skin daily after application of serums. Ideal baseline for morning refreshing steps.",
        "ingredients": "Water, Glycerin, 3-O-Ethyl Ascorbic Acid, Aloe Barbadensis Leaf Juice Powder, Sesamum Indicum Seed Oil."
    },
    {
        "id": 39,
        "title": "Propolis Light Moisturizing Shield",
        "category": "Moisturizers",
        "brand": "COSRX",
        "image": "image/product_39.jpg",
        "price": 25.00,
        "qty": 85,
        "description": "Features high black bee propolis complex percentage delivering a healthy honey-like glow.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply a proper amount evenly on skin surface after dynamic toning steps, dab light to integrate.",
        "ingredients": "Propolis Extract, Butylene Glycol, Glycerin, Betaine, 1,2-Hexanediol, Cassia Obtusifolia Seed Extract, Sodium Hyaluronate."
    },
    {
        "id": 40,
        "title": "Cicaplast Baume B5+ Ultra Repair",
        "category": "Moisturizers",
        "brand": "La Roche-Posay",
        "image": "image/product_40.jpg",
        "price": 22.00,
        "qty": 110,
        "description": "Soothing therapeutic balm optimal for dry skin irritations and compromised barrier recovery.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply twice daily to pre-washed and dried skin layers. Can be applied in rich layers safely.",
        "ingredients": "Water, Hydrogenated Polyisobutene, Dimethicone, Glycerin, Butyrospermum Parkii (Shea) Butter, Panthenol (Vitamin B5), Centella Asiatica."
    },

    # ==================== TONERS (10 Products) ====================
    {
        "id": 18,
        "title": "Hydrating Milky Rice Toner",
        "category": "Toners",
        "brand": "I'm From",
        "image": "image/product_18.jpg",
        "price": 22.00,
        "qty": 65,
        "description": "Formulated with 77.78% Rice Extract to deeply nourish, soothe, and brighten dull skin.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "how_to_use": "Shake thoroughly to mix layers before use. Dispense onto palms or pads, rub gently into skin.",
        "ingredients": "Oryza Sativa (Rice) Extract, Methylpropanediol, Triethylhexanoin, Hydrogenated Poly, Niacinamide, Adenosine."
    },
    {
        "id": 19,
        "title": "AHA/BHA Exfoliating Glow Toner",
        "category": "Toners",
        "brand": "COSRX",
        "image": "image/product_19.jpg",
        "price": 24.00,
        "qty": 70,
        "description": "Mild chemical exfoliating toner that sweeps away dead skin cells for smooth radiance.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply onto a cotton pad after cleansing facial lines. Wipe gently. Use 3-4 times a week at night.",
        "ingredients": "Water, Salix Alba (Willow) Bark Water, Pyrus Malus (Apple) Fruit Water, Glycolic Acid (AHA), Salicylic Acid (BHA)."
    },
    {
        "id": 20,
        "title": "Green Tea Calming Liquid",
        "category": "Toners",
        "brand": "Isntree",
        "image": "image/product_20.jpg",
        "price": 20.00,
        "qty": 80,
        "description": "Soothing toner infused with Boseong Green Tea leaves to balance oil production.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "After washing your face, drop liquid onto cotton pads and massage outwards across cheeks.",
        "ingredients": "Camellia Sinensis (Green Tea) Leaf Extract, Water, Ginkgo Biloba Leaf Extract, Centella Asiatica Extract, Allantoin."
    },
    {
        "id": 21,
        "title": "Witch Hazel Pore-Tightening Mist",
        "category": "Toners",
        "brand": "Thayers",
        "image": "image/product_21.jpg",
        "price": 18.00,
        "qty": 120,
        "description": "Alcohol-free refreshing mist spray to tighten pores and prep skin for serums.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Hold bottle 6-8 inches from face. Close eyes and mist skin anytime throughout operational cycles.",
        "ingredients": "Hamamelis Virginiana (Witch Hazel) Extract, Aloe Barbadensis Leaf Juice, Glycerin, Citric Acid, Citrus Grandis (Grapefruit) Seed Extract."
    },
    {
        "id": 22,
        "title": "Cica Redness Relief Treatment",
        "category": "Toners",
        "brand": "Dr. Jart+",
        "image": "image/product_22.jpg",
        "price": 23.50,
        "qty": 50,
        "description": "Centella Asiatica skin tonic base built explicitly to bring immediate cooling to irritated skin layers.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply a moderate amount onto irritated skin patterns. Press with warmth of palms to absorb completely.",
        "ingredients": "Water, Centella Asiatica Extract, Eryngium Maritimum Extract, Houttuynia Cordata Extract, Achillea Millefolium Oil."
    },
    {
        "id": 41,
        "title": "Heartleaf 77% Soothing Toner",
        "category": "Toners",
        "brand": "Anua",
        "image": "image/product_41.jpg",
        "price": 26.00,
        "qty": 150,
        "description": "Highly calming toner infused with 77% heartleaf extract to target irritation and acne.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Use after cleansing in AM & PM. Pat gently into skin or leave soaked cotton pad on sensitive spots.",
        "ingredients": "Houttuynia Cordata Extract (77%), Water, 1,2-Hexanediol, Glycerin, Centella Asiatica Extract, Chamomilla Recutita Extract."
    },
    {
        "id": 42,
        "title": "BHA 2% Liquid Exfoliant",
        "category": "Toners",
        "brand": "Paula's Choice",
        "image": "image/product_42.jpg",
        "price": 35.00,
        "qty": 95,
        "description": "Cult-favorite fluid exfoliant to clear blackheads, shrink pores, and even out tone.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Apply gently with a cotton pad over entire face at night. Do not rinse out skin layers.",
        "ingredients": "Water, Methylpropanediol, Salicylic Acid (2%), Camellia Sinensis (Green Tea) Leaf Extract, Polysorbate 20, Sodium Hydroxide."
    },
    {
        "id": 43,
        "title": "Glow Tonic Exfoliating Toner",
        "category": "Toners",
        "brand": "Pixi",
        "image": "image/product_43.jpg",
        "price": 24.00,
        "qty": 60,
        "description": "Formulated with 5% Glycolic Acid to gently brighten and smooth skin texture.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Saturate a cotton pad with the tonic and sweep across face, neck and décolletage after cleaning.",
        "ingredients": "Water, Glycolic Acid, Sodium Hydroxide, Aloe Barbadensis Leaf Juice, Panax Ginseng Root Extract, Glycerin."
    },
    {
        "id": 44,
        "title": "Centella Unscented Witch-Hazel Free Toner",
        "category": "Toners",
        "brand": "Purito",
        "image": "image/product_44.jpg",
        "price": 21.00,
        "qty": 75,
        "description": "Essential-oil free skin soothing water perfect for hyper-reactive sensitive skin.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply an appropriate amount to either clean hands or a cotton pad and sweep across facial paths.",
        "ingredients": "Water, Centella Asiatica Extract, Sodium Hyaluronate, Panthenol, Madecassoside, Asiaticoside, Allantoin."
    },
    {
        "id": 45,
        "title": "Watermelon Glow PHA + BHA Pore-Tight Toner",
        "category": "Toners",
        "brand": "Glow Recipe",
        "image": "image/product_45.jpg",
        "price": 34.00,
        "qty": 40,
        "description": "Gentle dual-exfoliating properties providing pillow-soft skin results instantly.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "how_to_use": "Press into clean face and neck layers until fully absorbed. Avoid sensitive eye rims directly.",
        "ingredients": "Watermelon Fruit Extract, Glycerin, Gluconolactone (PHA), Salicylic Acid (BHA), Sodium Hyaluronate, Centella Asiatica."
    },

    # ==================== EYE CARE (11 Products) ====================
    {
        "id": 23,
        "title": "Caffeine Awake Eye Cream",
        "category": "Eye Care",
        "brand": "The Ordinary",
        "image": "image/product_23.jpg",
        "price": 26.00,
        "qty": 30,
        "description": "Energizing formula with caffeine and peptide complexes to significantly diminish dark circles.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Massage a small amount onto the eye contour morning and evening.",
        "ingredients": "Water, Caffeine, Maltodextrin, Glycerin, Propanediol, Epigallocatechin Gallatyl Glucoside, Hyaluronic Acid."
    },
    {
        "id": 24,
        "title": "Snail Mucin Peptide Eye Gel",
        "category": "Eye Care",
        "brand": "COSRX",
        "image": "image/product_24.jpg",
        "price": 25.00,
        "qty": 55,
        "description": "Lightweight gel that minimizes fine lines while restoring optimal moisture zones.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply after using essence or serum. Tap a small dot around outer eye orbits cleanly.",
        "ingredients": "Snail Secretion Filtrate, Glycerin, Niacinamide, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Hyaluronic Acid."
    },
    {
        "id": 25,
        "title": "Vitamin E Under-Eye Brightener",
        "category": "Eye Care",
        "brand": "The Body Shop",
        "image": "image/product_25.jpg",
        "price": 23.50,
        "qty": 42,
        "description": "Rich hydrating cream base packed with antioxidants to shield delicate skin from aging.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Dot cream around eye boundaries using ring fingers. Smooth in light featherweight circles.",
        "ingredients": "Water, Glycerin, Tocheryl Acetate, Butyrospermum Parkii (Shea) Butter, Rose Extract, Sodium Benzoate."
    },
    {
        "id": 26,
        "title": "Retinol Lift & Target Balm",
        "category": "Eye Care",
        "brand": "Glow Recipe",
        "image": "image/product_26.jpg",
        "price": 29.50,
        "qty": 38,
        "description": "A focused retinol treatment stick addressing crows feet wrinkles and texture anomalies.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "how_to_use": "Gently swipe stick under and around the eye area at night. Follow up with moisture sealing steps.",
        "ingredients": "Squalane, Retinol, Persea Gratissima (Avocado) Oil, Tocopherol, Bakuchiol, Ceramide NP."
    },
    {
        "id": 27,
        "title": "Hyaluronic Cooling Roller",
        "category": "Eye Care",
        "brand": "Inkey List",
        "image": "image/product_27.jpg",
        "price": 21.00,
        "qty": 85,
        "description": "Metal rollerball applicator containing concentrated serum fluid to de-puff eyes on contact.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Squeeze tube lightly to dispense fluid onto metal roller tip. Roll around orbital patterns gently.",
        "ingredients": "Water, Glycerin, Sodium Hyaluronate, Phenoxyethanol, Ethylhexylglycerin, Caffeine, Citric Acid."
    },
    {
        "id": 28,
        "title": "Avocado Deep Nourish Eye Butter",
        "category": "Eye Care",
        "brand": "Kiehl's",
        "image": "image/product_28.jpg",
        "price": 27.00,
        "qty": 40,
        "description": "An ultra-rich, buttery skin layer treatment providing hydration support overnight.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply creamy texture along orbital bone tracks. Tap gently until texture transforms slightly into water droplets.",
        "ingredients": "Water, Persea Gratissima (Avocado) Oil, Glycerin, Butyrospermum Parkii Butter, Sodium Chloride, Tocopherol."
    },
    {
        "id": 46,
        "title": "Ginseng + Retinol Revive Eye Serum",
        "category": "Eye Care",
        "brand": "Beauty of Joseon",
        "image": "image/product_46.jpg",
        "price": 24.00,
        "qty": 90,
        "description": "Combines dynamic ginseng root extract with liposomal retinol to resolve under-eye wrinkles.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Pump 1-2 times and apply it around the skin layers of the eyes. Use at night for maximum repair.",
        "ingredients": "Panax Ginseng Root Extract, Water, Glycerin, Retinol, Niacinamide, Sodium Hyaluronate, Ceramide NP."
    },
    {
        "id": 47,
        "title": "Hydro Gel Eye Cool Patches (60pcs)",
        "category": "Eye Care",
        "brand": "Mediheal",
        "image": "image/product_47.jpg",
        "price": 22.50,
        "qty": 100,
        "description": "Water-soluble mask patches delivering immediate cooling serum formulas directly under eyes.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Place patches onto under-eye tracks using tool. Leave for 15-20 minutes, discard patches, tap excess fluid.",
        "ingredients": "Water, Glycerin, Chondrus Crispus Powder, Collagen, Sodium Hyaluronate, Allantoin, Centella Asiatica."
    },
    {
        "id": 48,
        "title": "Fermentation Galactomyces Eye Cream",
        "category": "Eye Care",
        "brand": "Benton",
        "image": "image/product_48.jpg",
        "price": 26.00,
        "qty": 35,
        "description": "Fermented extracts with bifida lysates combine forces to brighten and lift eye curves.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "how_to_use": "Apply an appropriate amount around the eyes and tap lightly to help skin cells absorb it.",
        "ingredients": "Galactomyces Ferment Filtrate, Bifida Ferment Lysate, Water, Glycerin, Peptide Complexes, Ceramide NP."
    },
    {
        "id": 49,
        "title": "Illuminating Pearl Eye Treatment",
        "category": "Eye Care",
        "brand": "Kiehl's",
        "image": "image/product_49.jpg",
        "price": 32.00,
        "qty": 50,
        "description": "Light-reflecting minerals create instant corrective visual changes to persistent dark circles.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "how_to_use": "Apply gently in the AM to instantly mask dark circles and activate structural light-reflection properties.",
        "ingredients": "Water, Pearl Extract, Titanium Dioxide, Glycerin, Dimethicone, Mica, Tocopheryl Acetate, Phenoxyethanol."
    },
    {
        "id": 50,
        "title": "Centella Green Level Calming Eye Cream",
        "category": "Eye Care",
        "brand": "Purito",
        "image": "image/product_50.jpg",
        "price": 20.00,
        "qty": 65,
        "description": "Formulated with safe clean ingredients protecting sensitive skin zones safely against aging.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "how_to_use": "Dab a small amount around the orbital ridge safely. Best integrated at the end of moisturizing routines.",
        "ingredients": "Centella Asiatica Extract, Water, Glycerin, Palmitoyl Hexapeptide-12, Palmitoyl Tripeptide-1, Panthenol."
    }
]

next_id = 51